atom:
  buildCommand:
    - /home/walter/gems/bin/jekyll
    - build
#    - --option
#    - --this
#  buildEnv:
#    JEKYLL_ENV: development
#  postDirs:
#    - _newsletters
#  defaultPostDir: _drafts

# set some common post defaults
defaults:
  - scope:
      path: "assets/images"
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      image: true
      layout: "post" # set the correct default template for a post
      section: "post" # set the root section name

encoding: utf-8
title: Interactive art by Kalwalt
email: info@kalwaltart.it
description: >
  Pagina web ufficiale per applicazioni interattive di Kalwalt.
name: Walter Perdan
author: Walter Perdan
logo: "/assets/images/logo_kalwalt_600x60.png"
#paginate:	5 # The number of posts to show per page on your homepage
#paginate_path: "/blog/page:num/"
# Pagination Settings
pagination:
  enabled: true
  per_page: 5
  offset: 0
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

google_site_verification:
baseurl: ""
url: https://www.kalwaltart.com
# Permalink format (/blog/ is ignored for pages)
permalink: /blog/:year/:month/:day/:title/

# Enable section IDs in frontmatter, useful for identifying current page
# (used as a hook for styling etc)
section: true

# set to 'true' to enable Netlify CMS (/admin) in production builds
netlifycms: true

# set to 'true' to enable Google Analytics tracking code in production builds
analytics: false

# Compress CSS
sass:
  style: compressed
  sass_dir: _sass

# Compress HTML (in liquid via layouts/compress.html)
compress_html:
  clippings: all

breadcrumbs:
  root:
    hide: false  # show breadcrumbs on root/home page
    image: false # Show image or title text

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-amp-pwa-plugin

# jekyll-tagging variables
tag_page_layout: tag_page
tag_page_dir: tag
tag_page_data:
  sitemap: false
tag_permalink_style: pretty

pwa:
  dest_js_directory: assets/js
  cache_name: pwa-cache
  precache_recent_posts_num: 12
  precache_glob_directory: /
  precache_glob_patterns:
    - "{js,css,fonts}/**/*.{js,css,woff,woff2,json}"
    - /assets/icons/*.png
    - /index.html
    - /offline.html
    - /about.html
  precache_glob_ignores:
    - sw-register.js
  strategy: cacheFirst

twitter:
  username: kalwalt
github_username: kalwalt
# Google Analytics
analytics_id: ""
markdown: kramdown
#permalink: /blog/:year/:month/:day/:title
github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
  # Prevent IDs from being added to h1-h6 tags
  auto_ids: false
future: true
jailed: false
gfm_quirks: paragraph_end
collections:
  stories:
    output: true
# Exclude from processing.
# The following items will not be processed.
exclude:
  - README.md
  - LICENSE.txt
  - netlify.toml
  - feed.xml
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - [vendor]
