<<<<<<< HEAD
atom:
  buildCommand:
    - jekyll
    - build
    - --option
    - --this
  buildEnv:
    JEKYLL_ENV: development
  postDirs:
    - _newsletters
  defaultPostDir: _drafts
name: Walter Perdan
#theme: jekyll-theme-architect
#theme: jekyll-theme-minima
markdown: kramdown
#permalink: /blog/:year/:month/:day/:title
=======
#name: Walter Perdaan
theme: jekyll-theme-architect
#markdown: kramdown
#permalink: /blog/:year/:month/:day/:title

>>>>>>> 19c07dcc9bbbd6a66c313df7427e33e649684d8c
