atom:
  buildCommand:
    - /home/walter/gems/bin/jekyll
    - build
#    - --option
#    - --this
#  buildEnv:
#    JEKYLL_ENV: development
#  postDirs:
#    - _newsletters
#  defaultPostDir: _drafts
encoding: utf-8
title: Interactive art by Kalwalt
email: info@kalwaltart.it
description: >
  Official Kalwalt website for interactive applications
name: Walter Perdan
author: Walter Perdan
logo: "/assets/images/logo_kalwalt_600x60.png"
paginate:	5 # The number of posts to show per page on your homepage
paginate_path: "/blog/page:num/"
google_site_verification: cC3276h9Hn4i0CmY109jtXIAAv8edaU7XJRkBLUOjLM
url: https://www.kalwaltart.it
baseurl: ""
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-minifier
twitter:
  username: kalwalt
github_username: kalwalt
# Google Analytics
analytics_id: "UA-114030597-1"
markdown: kramdown
#permalink: /blog/:year/:month/:day/:title
github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end
