atom:
  buildCommand:
    - home/walter/gems/bin/jekyll
    - build
#    - --option
#    - --this
#  buildEnv:
#    JEKYLL_ENV: development
#  postDirs:
#    - _newsletters
#  defaultPostDir: _drafts
name: Walter Perdan
author: Walter Perdan
lang: en_US
description: Original website of Kalwalt alias Walter Perdan. In this website are stored all my augmented reality applications
plugins:
  - jekyll-seo-tag
twitter:
  username: kalwalt
#theme: jekyll-theme-architect
#theme: jekyll-theme-minima
#markdown: kramdown
#permalink: /blog/:year/:month/:day/:title
