atom:
  buildCommand:
    - home/walter/gems/bin/jekyll
    - build
#    - --option
#    - --this
#  buildEnv:
#    JEKYLL_ENV: development
#  postDirs:
#    - _newsletters
#  defaultPostDir: _drafts
name: Walter Perdan
author: Walter Perdan
google_site_verification: cC3276h9Hn4i0CmY109jtXIAAv8edaU7XJRkBLUOjLM
url: https://kalwalt.github.io/
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
twitter:
  username: kalwalt
#theme: jekyll-theme-architect
#theme: jekyll-theme-minima
#markdown: kramdown
#permalink: /blog/:year/:month/:day/:title
