atom:
  buildCommand:
    - /home/walter/gems/bin/jekyll
    - build
#    - --option
#    - --this
#  buildEnv:
#    JEKYLL_ENV: development
#  postDirs:
#    - _newsletters
#  defaultPostDir: _drafts
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

encoding: utf-8
title: Interactive art by Kalwalt
email: info@kalwaltart.it
description: >
  Official Kalwalt website for interactive applications
name: Walter Perdan
author: Walter Perdan
logo: "/assets/images/logo_kalwalt_600x60.png"
paginate:	5 # The number of posts to show per page on your homepage
paginate_path: "/blog/page:num/"
google_site_verification: cC3276h9Hn4i0CmY109jtXIAAv8edaU7XJRkBLUOjLM
url: https://www.kalwaltart.it
baseurl: ""
# Permalink format (/blog/ is ignored for pages)
permalink: /blog/:title

# Enable section IDs in frontmatter, useful for identifying current page
# (used as a hook for styling etc)
section: true

# set to 'true' to enable Netlify CMS (/admin) in production builds
netlifycms: true

# set to 'true' to enable Google Analytics tracking code in production builds
analytics: false

# Compress CSS
sass:
  style: compressed
  sass_dir: _sass

# Compress HTML (in liquid via layouts/compress.html)
compress_html:
  clippings: all

# options for responsive_image plugin
responsive_image:
  template: _includes/responsive-image.html
  sizes:
   - width: 600
   - width: 480

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-pwa-plugin
  - jekyll-responsive-image

# set some common post defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post" # set the correct default template for a post
      section: "post" # set the root section name
pwa:
  sw_filename: sw.js
  dest_js_directory: assets/js
  cache_name: pwa-cache
  precache_recent_posts_num: 12
  precache_glob_directory: /
  precache_glob_patterns:
    - "{js,css,fonts}/**/*.{js,css,woff,woff2}"
    - /index.html
    - /about.html
  precache_glob_ignores:
    - sw-register.js
  strategy: cacheFirst

twitter:
  username: kalwalt
github_username: kalwalt
# Google Analytics
analytics_id: "UA-114030597-1"
markdown: kramdown
#permalink: /blog/:year/:month/:day/:title
github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
  # Prevent IDs from being added to h1-h6 tags
  auto_ids: false
future: true
jailed: false
gfm_quirks: paragraph_end
collections:
  stories:
    output: true
# Exclude from processing.
# The following items will not be processed.
exclude:
  - README.md
  - LICENSE.txt
  - netlify.toml
  - feed.xml
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
